package edu.hnu.gpsa.core;

public enum Signal {

	MANAGER_ITERATION_START,
	MANAGER_ITERATION_OVER,
	MANAGER_ITERATION_COMPUTE_OVER,
	DISPATCHER_ITERATION_DISPATCH_OVER,
	DISPATCHER_ITERATION_DISPATCH_START,
	DISPATCHER_ITERATION_COMPUTE_OVER,
	COMPUTER_COMPUTE_OVER,
	SYSTEM_OVER
	
}
